global:
  scrape_interval: 15s

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape ingress (auto-discovers ALL replicas)
  - job_name: 'ingress'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [ __meta_kubernetes_service_name ]
        regex: ingress
        action: keep
      - source_labels: [ __meta_kubernetes_namespace ]
        regex: hive-pulse
        action: keep
      - source_labels: [ __meta_kubernetes_endpoint_port_name ]
        regex: metrics
        action: keep

  # Scrape consumer (auto-discovers ALL replicas)
  - job_name: 'consumer'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        regex: consumer
        action: keep
      - source_labels: [__meta_kubernetes_namespace]
        regex: hive-pulse
        action: keep
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        regex: metrics
        action: keep
