---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-pvc
  namespace: hive-pulse
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # 40Gi+ for production (10K RPS, TTL - 24 hours)

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
  namespace: hive-pulse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
        - name: clickhouse
          image: clickhouse/clickhouse-server:23.12
          ports:
            - containerPort: 9000  # TCP ClickHouse client
            - containerPort: 8123  # HTTP interface
          volumeMounts:
            - name: clickhouse-data
              mountPath: /var/lib/clickhouse
      volumes:
        - name: clickhouse-data
          persistentVolumeClaim:
            claimName: clickhouse-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: hive-pulse
spec:
  type: ClusterIP
  selector:
    app: clickhouse
  ports:
    - port: 9000
      targetPort: 9000
      name: tcp
    - port: 8123
      targetPort: 8123
      name: http

---
apiVersion: batch/v1
kind: Job
metadata:
  name: clickhouse-init
  namespace: hive-pulse
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: clickhouse-init
          image: clickhouse/clickhouse-server:23.12
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo 'Waiting for ClickHouse to be ready...';
              until clickhouse-client --host clickhouse --query "SELECT 1" >/dev/null 2>&1; do
                sleep 2;
              done;
              echo 'Executing init.sql...';
              clickhouse-client --host clickhouse --multiquery < /init/init.sql;
              echo 'Initialization completed!';
          volumeMounts:
            - name: init-sql
              mountPath: /init/init.sql
              subPath: init.sql
      volumes:
        - name: init-sql
          configMap:
            name: clickhouse-init-sql
