apiVersion: apps/v1
kind: Deployment
metadata:
  name: emqx
  labels:
    app: emqx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emqx
  template:
    metadata:
      labels:
        app: emqx
    spec:
      containers:
        - name: emqx
          image: emqx/emqx:5.3.0
          env:
            - name: EMQX_ALLOW_ANONYMOUS
              value: "true"
            - name: EMQX_LISTENER__TCP__EXTERNAL
              value: "1883"
            - name: EMQX_LISTENER__WS__EXTERNAL
              value: "9001"
            - name: EMQX_LOG__LEVEL
              value: "debug"
            - name: EMQX_CONNECTION__MAX
              value: "50000"
            - name: EMQX_FORCE_SHUTDOWN__ENABLE
              value: "false"
          ports:
            - containerPort: 1883
            - containerPort: 9001
            - containerPort: 18083
---
apiVersion: v1
kind: Service
metadata:
  name: emqx
spec:
  type: NodePort
  selector:
    app: emqx
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
      nodePort: 31883

    - name: ws
      port: 9001
      targetPort: 9001
      nodePort: 32001

    - name: dashboard
      port: 18083
      targetPort: 18083
      nodePort: 32083
