networks:
  shared-net:
    external: true

services:
  kafka:
    container_name: kafka
    image: bitnamilegacy/kafka:latest
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
    volumes:
      - kafka_data:/bitnamilegacy/kafka
    networks:
      - shared-net

  kafka-init:
    container_name: kafka-init
    image: bitnamilegacy/kafka:latest
    depends_on:
      - kafka
    entrypoint: >
      /bin/bash -c "
      echo 'Waiting for Kafka to be ready...';
      until kafka-topics.sh --bootstrap-server kafka:9092 --list >/dev/null 2>&1; do
        sleep 2;
      done;
      echo 'Creating topic device_telemetry...';
      kafka-topics.sh --bootstrap-server kafka:9092 --create --topic device_telemetry --partitions 12 --replication-factor 1;
      echo 'Topic created!';
      "
    restart: "no"
    networks:
      - shared-net

volumes:
  kafka_data:
