---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: hive-pulse
spec:
  replicas: 2
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: localhost:5000/consumer:latest
          ports:
            - containerPort: 2112
              name: metrics
          env:
            - name: BATCH_SIZE
              value: "10000"
            - name: CLICKHOUSE_DB
              value: "default"
            - name: CLICKHOUSE_DSN
              value: "clickhouse:9000"
            - name: CLICKHOUSE_PASSWORD
              value: ""
            - name: CLICKHOUSE_TABLE
              value: "device_data"
            - name: CLICKHOUSE_USERNAME
              value: "default"
            - name: KAFKA_BROKER
              value: "kafka:9092"
            - name: KAFKA_TOPIC
              value: "device_telemetry"
            - name: KAFKA_GROUP_ID
              value: "device_consumers"

---
apiVersion: v1
kind: Service
metadata:
  name: consumer
  namespace: hive-pulse
spec:
  type: ClusterIP
  selector:
    app: consumer
  ports:
    - port: 2112
      targetPort: 2112
      name: metrics
